spring.application.name=SpringBootJPA

spring.datasource.url=jdbc:mysql://localhost:3306/hibernate
spring.datasource.username=root
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.password=root


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect